[package]
name = "compressible_fluids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools-num = "*"
csv = "*"
libmath = "*"
ndarray = "*"
<<<<<<< HEAD
=======
hdf5 = "*"
>>>>>>> e6db99b8c7904d7d629d2cf6537da62db6d1cb8b
