[package]
name = "compressible_fluids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools-num = "*"
csv = "*"
libmath = "*"
ndarray = "*"
num-traits = "0.2.15"
rayon = "1.5.3"
